### Get all contacts (GET)
GET http://localhost:5000/contacts
Accept: application/json

### Get Contact by ID using valid and existing ID (GET)
GET http://localhost:5000/contacts/678c6ed81e034ad4b04794b6
Accept: application/json

### Get Contact by ID using non-existing ID (GET)
GET http://localhost:5000/contacts/65b5e8c4d6f3c9b1f0a1b2c3
Accept: application/json

### Create a new contact (POST)
POST http://localhost:5000/contacts
Content-Type: application/json

{
    "firstName": "Joseph",
    "lastName": "Ervin",
    "email": "johnervin@example.com",
    "favoriteColor": "Blue",
    "birthday": "July 26"
}

### Update an existing contact (PUT)
PUT http://localhost:5000/contacts/679d60c91388ba937eccc45b
Content-Type: application/json

{
    "firstName": "John",
    "email": "johnervin@example.com",
    "favoriteColor": "Purple"
}

### Delete a contact (DELETE)
DELETE http://localhost:5000/contacts/679d63f3432832180b72e91e