# LOCAL HOST - DEVELOPMENT #

### Get all contacts (GET)
GET http://localhost:5000/contacts
Accept: application/json

### Get Contact by ID using valid and existing ID (GET)
GET http://localhost:5000/contacts/678c6ed81e034ad4b04794b6
Accept: application/json

### Get Contact by ID using non-existing ID (GET)
GET http://localhost:5000/contacts/65b5e8c4d6f3c9b1f0a1b2c3
Accept: application/json